### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by carpad88** [Agilo/medusawp#31]
I got this error `Plugin could not be activated because it triggered a fatal error.` Trying to install the plugin in a fresh installation of WordPress 6.4.2. The plugin version is `0.3.3`

Also, I noticed when installing the plugin using composer another plugin is installed as well `Action Scheduler` but anywhere in the docs says something about it. Is this intended?

**Comment by anteprimorac** [comment]
Hi @carpad88, thank you for submitting the issue.

Yes, the Action Scheduler is part of the installation. It's used for background tasks like importing thumbnails into the WP Media Library.

Regarding the error, which PHP version are you using?

**Comment by carpad88** [comment]
Hi, the PHP version is 8.3.

Worth mentioning that I tried to run it a local environment using Laravel herd, I don't know if this has something to do with the error but I don't think so.

**Comment by anteprimorac** [comment]
@carpad88, we published a new `0.4.0` version. Can you check if it resolves your issue?

**Comment by carpad88** [comment]
I updated the package to version `0.4.0` but I'm still getting the same error. This is my server config

<img width="800" alt="Screenshot 2023-12-11 at 21 02 56" src="https://github.com/Agilo/medusawp/assets/13703238/0d72611d-24e2-4711-8ea6-a930c57f6b2c">

And this is the WordPress config:

<img width="796" alt="Screenshot 2023-12-11 at 21 04 15" src="https://github.com/Agilo/medusawp/assets/13703238/8d6b0aba-dd01-423d-a013-bcde5ca05690">

**Comment by anteprimorac** [comment]
@carpad88, could you take a look into the logs and get us the actual error you get?

**Comment by anteprimorac** [comment]
@carpad88, we pushed a new release where we changed how the plugin loads Action Scheduler, which should resolve the issue with activating the plugin. Please let us know if the issue persists.

**Comment by carpad88** [comment]
@anteprimorac I tried the new version; this time, I could install the plugin but found some issues when using it. 

For example, clicking on the settings menu gave me this error:

`File doesn't exist in /Users/carlos/Herd/example/wp-admin/includes/misc.php on line 4582`

After digging a little, I found the missing file was this:

`example/wp-content/plugins/medusawp//admin/dist/.vite/manifest.json`

So, to make it work I run `npm install` inside the plugin folder but when trying to run `npm build` I was getting missing dependencies, like `date-fns` and `loads/range`. I installed those, and when I finally got the settings screen to connect with the Medusa store, the following error appeared tons of times:

`Warning: Undefined array key "isEntry" in /Users/carlos/Herd/example/wp-content/plugins/medusawp/src/Admin.php on line 157
`
When I tried to connect to the medusa server I coudln't sync anything. From the error show on the browserr console I got this response from Medusa server:

```
{
    "message": "[401] Client error: `POST http://localhost:9000/wordpress/connect` resulted in a `401 Unauthorized` response:\n{\"message\":\"relation \\\"public.wordpress\\\" does not exist\"}\n"
}
```

**Comment by anteprimorac** [comment]
@carpad88, the latest error is a missing migration. You can run `npx medusa migrations run` in the medusa directory. Thank you for reporting other issues. We are going to fix those in the next release.

**Comment by carpad88** [comment]
@anteprimorac After running Medusa migrations, I could connect WordPress with Medusa; however, nothing got synced. I get the following screen, but nothing happens from there.

<img width="1174" alt="Screenshot 2023-12-20 at 23 16 53" src="https://github.com/Agilo/medusawp/assets/13703238/a4a7b8f5-5a2a-44ff-a5bf-bdbaa64a2111">

**Comment by anteprimorac** [comment]
@carpad88 hi, sorry for the late response. I missed your latest reply because the issue was closed.

Your issue is related to your local setup. Medusa is not able to connect back to WP. We resolve this for our development environment by assigning the local domain `medusawp.test` to the local IP address of the WP instance. I'm not sure what you use for your local development, but I assume there is documentation for your tool to configure similar things.
